id: A2C52FFDD
title: 'A Drop of Moonlight: A Guru Yoga for Lord Mila'
type: translation
pechas:
- I53775057
- I80674922
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:45:08.066235
  last_modified_at: 2023-01-04 12:45:08.066255
  collections:
  - Jokyab Pema Trinlé Nyingpo
  - Works of Tibetan Masters
alignment_to_base:
  I53775057/4A3A: 22BB
  I80674922/59AF: 22BB
